return function(palette, styles)
	return {
		BlinkCmpDoc = { bg = palette.hl1 },
		BlinkCmpDocSeparator = { bg = palette.hl1 },
		BlinkCmpDocBorder = { fg = palette.hl3 },
		BlinkCmpGhostText = { fg = palette.muted },

		BlinkCmpLabel = { fg = palette.muted },
		BlinkCmpLabelDeprecated = { fg = palette.muted, strikethrough = true },
		BlinkCmpLabelMatch = { fg = palette.fg, bold = styles.bold },

		BlinkCmpDefault = { fg = palette.hl2 },
		BlinkCmpKindText = { fg = palette.grn },
		BlinkCmpKindMethod = { fg = palette.blu },
		BlinkCmpKindFunction = { fg = palette.blu },
		BlinkCmpKindConstructor = { fg = palette.blu },
		BlinkCmpKindField = { fg = palette.grn },
		BlinkCmpKindVariable = { fg = palette.mgt },
		BlinkCmpKindClass = { fg = palette.ylw },
		BlinkCmpKindInterface = { fg = palette.ylw },
		BlinkCmpKindModule = { fg = palette.blu },
		BlinkCmpKindProperty = { fg = palette.blu },
		BlinkCmpKindUnit = { fg = palette.grn },
		BlinkCmpKindValue = { fg = palette.red },
		BlinkCmpKindKeyword = { fg = palette.blu2 },
		BlinkCmpKindSnippet = { fg = palette.mgt },
		BlinkCmpKindColor = { fg = palette.red },
		BlinkCmpKindFile = { fg = palette.blu },
		BlinkCmpKindReference = { fg = palette.red },
		BlinkCmpKindFolder = { fg = palette.blu },
		BlinkCmpKindEnum = { fg = palette.blu },
		BlinkCmpKindEnumMember = { fg = palette.blu },
		BlinkCmpKindConstant = { fg = palette.ylw },
		BlinkCmpKindStruct = { fg = palette.blu },
		BlinkCmpKindEvent = { fg = palette.blu },
		BlinkCmpKindOperator = { fg = palette.blu },
		BlinkCmpKindTypeParameter = { fg = palette.blu2 },
		BlinkCmpKindCodeium = { fg = palette.blu },
		BlinkCmpKindCopilot = { fg = palette.blu },
		BlinkCmpKindSupermaven = { fg = palette.blu },
		BlinkCmpKindTabNine = { fg = palette.blu },
	}
end
